openapi: 3.0.0
info:
  description: API for ordering computers from IT
  version: "1.0.0"
  title: Computer Orders API
paths:
  /orders/computers:
    get:
      summary: Retrieves all computer orders
      operationId: getComputerOrders
      description: Retrieves all the computer orders that have been created.
      responses:
        '200':
          description: All computer orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ComputerOrder'
        '400':
          description: Bad input parameter
    post:
      summary: Adds a computer order
      operationId: addInventory
      description: Creates a computer order by setting an order in the QUEUED state.
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ComputerOrder'
        description: Computer order that was created
      responses:
        '201':
          description: Computer order created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ComputerOrder'
        '400':
          description: 'Invalid input, object invalid'
components:
  schemas:
    ComputerOrder:
      type: object
      required:
        - id
        - status
        - created_by
        - created_at
        - equipment
      properties:
        id:
          type: string
          example: '1'
        status:
          $ref: '#/components/schemas/Status'
        created_by:
          type: string
          example: 'USER1'
        created_at:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        equipment:
          type: array
          items:
            $ref: '#/components/schemas/Equipment'
    Equipment:
      type: string
      enum:
        - KEYBOARD
        - MOUSE
        - WEBCAM
        - MONITOR
    Status:
      type: string
      enum:
        - QUEUED
        - PROCESSING
        - COMPLETED
        - FAILED